@PGRFacilAPI.Presentation_HostAddress = https://localhost:52545

POST https://localhost:52545/API/Acessos/Login
Accept: text/plain
Content-Type: application/json

{
  "email": "teste@teste.com",
  "senha": "Loki@123"
}

###
