// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PGRFacilAPI.Persistance;

#nullable disable

namespace PGRFacilAPI.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117063355_SchemaInicial")]
    partial class SchemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PGRFacilAPI.Domain.Models.Risco", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgentesDeRisco")
                        .HasColumnType("integer");

                    b.Property<string>("Atividades")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Danos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Perigos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Probabilidade")
                        .HasColumnType("bigint");

                    b.Property<long>("Severidade")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDeAvaliacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Riscos");
                });
#pragma warning restore 612, 618
        }
    }
}
